### ISSUE TITLE
Standard preset always appears disabled

### ISSUE THREAD

**Issue by mrapoc** [cammurray/orca#269]
I have checked across multiple tenants using Standard Preset and they all appear as disabled in the report.

**Comment by cammurray** [comment]
Hi @mrapoc confirming here, in tenants that have "Standard Preset" applied to both EOP/MDO, those policies are appearing disabled?

**Comment by mrapoc** [comment]
Hi

Correct yes showing as a disabled policy
________________________________

**Comment by CW-RKR** [comment]
I can confirm this too. There is a screenshot in my issue (https://github.com/cammurray/orca/issues/265) where you can see it. The round red dot with the number 1.

**Comment by cammurray** [comment]
@CW-RKR @mrapoc 

Turns out this is due to a consistency issue with how the preset policies are applied and normal policies.

I believe this is fixed now - and looking at the report you sent me @CW-RKR, certainly appears that's the case - in that report you sent, Standard policy is appearing correctly as applied and Strict is not. 

Can I get some confirmation on the behaviour you see in 2.7.1?

**Comment by mrapoc** [comment]
Hey Cam

I still get disabled next to the Standard Preset Security Policy on 2.7.1

**Comment by cammurray** [comment]
Re-opening this for investigation..
